/**
 * Copyright IBM Corp. 2021, 2026
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'aRecordSet', { get: function () { return require('./a-record-set'); } });
Object.defineProperty(exports, 'aaaaRecordSet', { get: function () { return require('./aaaa-record-set'); } });
Object.defineProperty(exports, 'cnameRecord', { get: function () { return require('./cname-record'); } });
Object.defineProperty(exports, 'mxRecordSet', { get: function () { return require('./mx-record-set'); } });
Object.defineProperty(exports, 'nsRecordSet', { get: function () { return require('./ns-record-set'); } });
Object.defineProperty(exports, 'ptrRecord', { get: function () { return require('./ptr-record'); } });
Object.defineProperty(exports, 'srvRecordSet', { get: function () { return require('./srv-record-set'); } });
Object.defineProperty(exports, 'txtRecordSet', { get: function () { return require('./txt-record-set'); } });
Object.defineProperty(exports, 'dataDnsARecordSet', { get: function () { return require('./data-dns-a-record-set'); } });
Object.defineProperty(exports, 'dataDnsAaaaRecordSet', { get: function () { return require('./data-dns-aaaa-record-set'); } });
Object.defineProperty(exports, 'dataDnsCnameRecordSet', { get: function () { return require('./data-dns-cname-record-set'); } });
Object.defineProperty(exports, 'dataDnsMxRecordSet', { get: function () { return require('./data-dns-mx-record-set'); } });
Object.defineProperty(exports, 'dataDnsNsRecordSet', { get: function () { return require('./data-dns-ns-record-set'); } });
Object.defineProperty(exports, 'dataDnsPtrRecordSet', { get: function () { return require('./data-dns-ptr-record-set'); } });
Object.defineProperty(exports, 'dataDnsSrvRecordSet', { get: function () { return require('./data-dns-srv-record-set'); } });
Object.defineProperty(exports, 'dataDnsTxtRecordSet', { get: function () { return require('./data-dns-txt-record-set'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

